In [10]:
from lab.mplc.experiments.mplc_qkd_random_phases import modes_to_keep
from pianoq_results.scan_result import ScanResult
res_sig = ScanResult()
res_idl = ScanResult()
# path = r"G:\My Drive\Projects\MPLC\results\lab\2024_09_05_QKD_random_phases\2024_09_08_14_57_00_QKD_MUB2_signal_res_4.scan"
# path = r"G:\My Drive\Projects\MPLC\results\lab\2024_09_05_QKD_random_phases\2024_09_08_14_46_42_QKD_MUB2_idler_res_4.scan"

path_idl = r"G:\My Drive\Projects\MPLC\results\lab\2024_09_05_QKD_random_phases\2024_09_08_15_21_56_QKD_MUB2_idler_res_1.scan"
path_sig = r"G:\My Drive\Projects\MPLC\results\lab\2024_09_05_QKD_random_phases\2024_09_08_15_21_56_QKD_MUB2_signal_res_1.scan"
res_idl.loadfrom(path_idl)
res_sig.loadfrom(path_sig)
res_idl.show_singles()
res_sig.show_singles()

In [9]:
res_sig.get_xys(2, saveto_dir="C:\\temp")
res_idl.get_xys(1, saveto_dir=dir)

Saved to C:\temp\2024_09_08_15_40_28_s2_sig.locs


[(9.136174242424243, 1.5737554112554113),
 (9.188528138528138, 1.7482683982683984),
 (9.15944264069264, 1.9053300865800866),
 (9.16525974025974, 2.0682088744588745),
 (9.066369047619048, 2.2369047619047624)]

In [4]:
path = r"G:\My Drive\Projects\MPLC\results\lab\2024_09_05_QKD_random_phases\2024_09_09_10_30_23_QKD_MUB2_good_exp_4s.scan"
from pianoq.lab.mplc.discrete_scan_result import DiscreetScanResult
r = DiscreetScanResult()
r.loadfrom(path)
r.show_singles()
r.show(False)

In [12]:
import numpy as np 
import matplotlib.pyplot as plt
from pianoq.lab.mplc.phase_finder_result import PhaseFinderResult
r1 = PhaseFinderResult()
r2 = PhaseFinderResult()
r1.loadfrom(r"G:\My Drive\Projects\MPLC\results\lab\2024_09_05_QKD_random_phases\2024_09_09_09_25_32_QKD_MUB2_signal.phases")
r2.loadfrom(r"G:\My Drive\Projects\MPLC\results\lab\2024_09_09_QKD_random_phases\2024_09_09_13_44_45_QKD_MUB2_signal.phases")
modes_to_keep = np.array([3, 8, 13, 18, 23, 28, 33, 38, 43, 48]) - 1
display(r1.phases[modes_to_keep])
display(r2.phases[modes_to_keep])

fig, ax = plt.subplots()
ax.plot(r1.phases[modes_to_keep], label="old")
ax.plot(r2.phases[modes_to_keep], label="new")
fig.legend()

array([5.27195142, 1.06204488, 1.0662511 , 0.64159401, 5.81194364,
       0.39239066, 0.3575338 , 6.27549975, 0.07658275, 0.01601564])

array([5.32763157, 1.13888194, 1.16319575, 0.62473823, 5.20208745,
       0.13364829, 6.19309335, 6.15554079, 0.27453943, 6.017723  ])

In [14]:
import numpy as np 
phases = np.random.uniform(0, 2*np.pi, 50)
np.savez("C:\\temp\\randz", phase=phases)

In [17]:
data = np.load("C:\\temp\\randz.npz")
data['phase']

array([1.74408845, 4.17655184, 6.05893926, 3.49041986, 0.51201175,
       5.5431441 , 5.92206268, 1.46085017, 4.0556407 , 0.35037056,
       3.4720358 , 5.63839309, 4.56287119, 0.46784062, 1.98377082,
       4.51661892, 5.10135942, 2.85948033, 4.43783755, 1.85034968,
       1.03792575, 4.50344636, 0.90307841, 0.39719016, 1.47016574,
       5.861324  , 1.36481104, 2.16035748, 3.68896957, 1.80510922,
       0.27587982, 4.25529694, 0.51954454, 5.16685521, 1.65771565,
       1.0616433 , 2.96375486, 1.25681191, 1.86062247, 6.15030239,
       4.53452487, 5.04496446, 1.78434155, 3.0143077 , 0.68656479,
       5.91907458, 3.90721865, 0.16347958, 5.77870828, 0.99901459])